import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold underline">hi mom</h1>
      <button className="border-2 border-black p-4 m-4">get request</button>
      <button className="border-2 border-black p-4 m-4">post request</button>
      <button className="border-2 border-black p-4 m-4">put request</button>
      <button className="border-2 border-black p-4 m-4">delete request</button>
    </div>
  );
}
