import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center items-center">
        <Link href={"/get"} className="border-2 border-black p-4 m-4">
          get request
        </Link>
        <Link href={"/post"} className="border-2 border-black p-4 m-4">
          post request
        </Link>
        <Link href={"/put"} className="border-2 border-black p-4 m-4">
          put request
        </Link>
        <Link href={"/patch"} className="border-2 border-black p-4 m-4">
          patch request
        </Link>
        <Link href={"/delete"} className="border-2 border-black p-4 m-4">
          delete request
        </Link>
      </div>
    </div>
  );
}
